//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserWeb.UserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/UserService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseService", Namespace="http://schemas.datacontract.org/2004/07/UserWeb.Dto")]
    [System.SerializableAttribute()]
    public partial class ResponseService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IWSUserService")]
    public interface IWSUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserService/GetUser", ReplyAction="http://tempuri.org/IWSUserService/GetUserResponse")]
        UserWeb.UserService.User[] GetUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserService/GetUser", ReplyAction="http://tempuri.org/IWSUserService/GetUserResponse")]
        System.Threading.Tasks.Task<UserWeb.UserService.User[]> GetUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserService/InsertUser", ReplyAction="http://tempuri.org/IWSUserService/InsertUserResponse")]
        UserWeb.UserService.ResponseService InsertUser(DataAccess.Dto.UserDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserService/InsertUser", ReplyAction="http://tempuri.org/IWSUserService/InsertUserResponse")]
        System.Threading.Tasks.Task<UserWeb.UserService.ResponseService> InsertUserAsync(DataAccess.Dto.UserDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserService/UpdateUser", ReplyAction="http://tempuri.org/IWSUserService/UpdateUserResponse")]
        UserWeb.UserService.ResponseService UpdateUser(DataAccess.Dto.UserDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserService/UpdateUser", ReplyAction="http://tempuri.org/IWSUserService/UpdateUserResponse")]
        System.Threading.Tasks.Task<UserWeb.UserService.ResponseService> UpdateUserAsync(DataAccess.Dto.UserDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserService/DeleteUser", ReplyAction="http://tempuri.org/IWSUserService/DeleteUserResponse")]
        UserWeb.UserService.ResponseService DeleteUser(DataAccess.Dto.UserDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserService/DeleteUser", ReplyAction="http://tempuri.org/IWSUserService/DeleteUserResponse")]
        System.Threading.Tasks.Task<UserWeb.UserService.ResponseService> DeleteUserAsync(DataAccess.Dto.UserDto user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSUserServiceChannel : UserWeb.UserService.IWSUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSUserServiceClient : System.ServiceModel.ClientBase<UserWeb.UserService.IWSUserService>, UserWeb.UserService.IWSUserService {
        
        public WSUserServiceClient() {
        }
        
        public WSUserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSUserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSUserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSUserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UserWeb.UserService.User[] GetUser() {
            return base.Channel.GetUser();
        }
        
        public System.Threading.Tasks.Task<UserWeb.UserService.User[]> GetUserAsync() {
            return base.Channel.GetUserAsync();
        }
        
        public UserWeb.UserService.ResponseService InsertUser(DataAccess.Dto.UserDto user) {
            return base.Channel.InsertUser(user);
        }
        
        public System.Threading.Tasks.Task<UserWeb.UserService.ResponseService> InsertUserAsync(DataAccess.Dto.UserDto user) {
            return base.Channel.InsertUserAsync(user);
        }
        
        public UserWeb.UserService.ResponseService UpdateUser(DataAccess.Dto.UserDto user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<UserWeb.UserService.ResponseService> UpdateUserAsync(DataAccess.Dto.UserDto user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public UserWeb.UserService.ResponseService DeleteUser(DataAccess.Dto.UserDto user) {
            return base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task<UserWeb.UserService.ResponseService> DeleteUserAsync(DataAccess.Dto.UserDto user) {
            return base.Channel.DeleteUserAsync(user);
        }
    }
}
